name: Upload production

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Upload
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.server_ftp_host }}
          username: ${{ secrets.server_ftp_user }}
          password: ${{ secrets.server_ftp_password }}
          local-dir: "./"
          exclude:  |
            **/.git*
            **/.git*/**
            /.git
            **/.github*
            **/.github*/**
            **/node_modules/**
            *.env
      - name: Install & restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ssh_host }}
          username: ${{ secrets.ssh_user }}
          password: ${{ secrets.ssh_password }}
          port: ${{ secrets.ssh_port }}
          script: |
            cd /home/discord-bot
            docker-compose down
            docker-compose build
            docker-compose up -d
